[Refactor] S3Util -> S3FileUtil & S3Util 로 기능별 분리
KUIT-AGARANG/Agarang-Backend pull request #20
Opened 2024-07-16 04:53 UTC by JGoo99

## #️⃣연관된 이슈

> ex) #이슈번호, #이슈번호

#17 

<br/>

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

#### 기존

- `S3Util` : 업로드의 모든 과정이 이루어짐.

#### 변경

- `S3File` : File 과 MultipartFile 이 섞여있어 로직을 이해하는데에 방해가 된다고 판단하여 S3File 객체를 생성하여 통일화했습니다.

- `S3FileUtil` : MultipartFile -> S3File 변환, 로컬에 임시파일 업로드 및 삭제 등 파일 자체와 관련된 작업을 수행합니다.

- `S3Util` : S3FileUtil 을 활용하여 S3 파일 서버에 업로드가 이루어집니다.

<br/>

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

application-secret.yml 업데이트 되었습니다!

아직은 음악과 추억공유 두 카테고리만 존재해서 디렉토리 유효성 검사 유형은 다음과 같습니다.
- 음악 카테고리인 경우 -> .mp3 이어야 함
- 음악 카테고리가 아닌 경우 -> .mp3 면 안 됨.

만약 디렉토리를 추가해서 카테고리 분류가 늘어난다면, 유효성 검사를 어떻게 디테일하게 진행할지 좀 더 고민해보겠습니다!

2024-07-16 08:58 UTC, rlagkswn00 requested changes
고생하셨습니다!
개인적으로 유효성 처리 부분과 FileCategory 클래스 사용 부분이 모호해서 제가 생각한 부분을 남겨봅니당😂

2024-07-16 08:58 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/global/s3/utils/S3Util.java
> +      s3FileUtil.uploadTempFile(s3File);
로컬에 파일저장하는게 upload메소드 실행 전에 저장하는 것이 임시로 파일을 저장하는 목적에 조금 더 부합하는거 같다는 생각이 듭니당

2024-07-16 08:58 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/global/s3/utils/S3FileUtil.java
> +  }
이부분이 단순 파일카테고리의 유효성을 검사하는 것보단 MP3, MUSIC이 두가지에만 국한되어 있어서 조금 더 수정이 필요한 부분일거 같습니다!

정확한 해결책이 떠오르진 않지만 개인적으론 FileCategory의 사용이 오히려 유효성 검사를 위해 모든 연결된 메소드가 FileCategory를 의존하게 되는 결과를 갖고 오는듯 합니다.

현재 코드에서 S3 업로드를 위해 외부에서 미리 파일의 카테고리를 판단해야 합니다. 
이를 외부에서 반복적으로 생성하는 것이 불필요할 수도 있다는 생각과 함께, 파일에 의존해서 카테고리를 구분하는 것이 아닌, 요구사항에 따라 FileCategory를 개발자가 직접 결정하는 것은 실수할 여지를 남겨두는 듯 해서 수정이 필요할거 같습니당!

말그대로 임시 저장이라면 디렉토리를 `temp/` 이상으로 더 깊게 만들어야할 필요가 있는지 개인적으로 고민 되는 부분입니다!(어차피 에러 발생 여부와 상관없이 로직 사용 직후 삭제되는 로직이기 때문)

또 다른 생각으로는 ContentType에 유효한 확장자명이 명시되어 있는데, 각 ContentType을 FileCategory에 매핑시켜두는 것도 괜찮지 않을까 싶습니당 (MP3, WAV -> MUSIC 등의 방식)

이부분 어렵네용 ㅠㅠ

2024-07-16 11:20 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/global/s3/utils/S3Util.java
> +      s3FileUtil.uploadTempFile(s3File);
늘 예리한 것 같아서 감탄중입니다.ㅎㅎ 반영하겠습니다! 감사합니다. 👍🏼👍🏼

2024-07-16 13:56 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/global/s3/utils/S3FileUtil.java
> +  }
> 임시 저장이라면 디렉토리를 temp/ 이상으로 더 깊게 만들어야할 필요가 있는지 개인적으로 고민 되는 부분...

오 이 부분 반영하겠습니다! 
서버에 있는 디렉토리명만 봐도 안에있는 파일이 어떤 의미의 파일인지 알아야 할까 싶어서 고민했던 부분이에요. (언젠가 로직 실수로 파일이 많이 쌓여있을 때, 해당 파일을 다른 개발자가 봐도 어떤 의미의 파일인지 알면 좋을 것 같다 생각했습니다.)

`./var/app/s3-uploads` 에서 `temp/uploads` 로 줄이겠습니다.

<br/>

> 파일에 의존해서 카테고리를 구분하는 것이 아닌, 요구사항에 따라 FileCategory를 개발자가 직접 결정하는 것은 실수할 여지를...

동감하는 부분입니다! 저도 여기서 많이 고민했습니다ㅠ

파일 확장자에 의존해서 카테고리를 구분하게되면,
이미지를 저장하는 s3 디렉토리(ex. `member`)를 추가했을 때, `/memory` 와 `/member` 를 구분할 방법이 없는 문제가 발생해요.
(두 디렉토리의 허용하는 확장자가 같기 때문.)

s3 버킷에 디렉토리로 `music`, `memory` 로 두개를 생성해둔 상황에서 만약 s3 에 디렉토리가 더 늘어난다면 어떤식으로 구별해야할까 싶어서 생각해본 방법이 FileCategory 를 같이 받는 거였어요!

- 추억공유 -> memeory 디렉토리로 매핑
- 음악 -> music 디렉토리로 매핑
- 회원 -> member 디렉토리로 매핑

여기서 발생하는 문제점은 한주님이 말씀해주신 것 처럼 개발자가 실수한 경우 예외처리할 방법이 없다는 것입니다...!

그래서 다시 원점으로 돌아가 s3 의 디렉토리를 없애는 것도 하나의 방법이 될 것 같습니다! (FileCategory 도 삭제)

```
1) 어짜피 s3 에서는 디렉토리도 하나의 키값으로써의 역할인데, 이미 UUID 로 파일명(키값)을 생성하기에 중복 가능성이 작다.

2) s3 디렉토리별 조회 기능이 생길 가능성이 없다. (사진 및 음악 모두 개인을 위한 정보이기 때문.)
```

2024-07-16 14:11 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/global/s3/utils/S3FileUtil.java
> +  }
다시 생각해보니 s3 의 폴더 구조가 불필요하다고 단정하기가 어려워서,
아예 폴더를 삭제하는 것 보다는 확장자 별로 폴더를 관리해도 좋을 것 같아요!

- mp3 -> `audio/ `
- jpg, jpeg, png -> `images/`

2024-07-16 15:35 UTC, JGoo99 commented
### 수정 사항

1. 로컬에 임시파일 업로드 시 `./temp/music` or `./temp/audio` 에 저장됩니다.

2. 로컬 임시파일 업로드는 s3 업로드 메소드 호출 전 수행합니다.

3. 로컬 임시파일 업로드 전에 디렉토리를 먼저 생성합니다. (no search file or directory 예외 방지)

4. 기존 FileCategory 별로 디렉토리를 구분하는 것에서 파일 확장자별로 구분하는 것으로 변경했습니다.
(외부에서는 MultipartFile 만 넘겨주면 됩니다. (실수 방지))

5. s3 파일명 생성 시 파일의 이름에 포함된 `/` `\` ` ` 는 모두  안전한 `_` 로 변경합니다.

2024-07-16 17:43 UTC, JGoo99 commented
### 수정 사항 2

S3File 에 objectUrl 필드를 추가하고, 업로드 성공 시 체이닝 메서드로 생성된 url 을 할당합니다.

```java
public S3File putObjectUrl(String objectUrl) {
  this.objectUrl = objectUrl;
  return this;
}
```

파일 조회는 objectUrl 로 가능합니다. 해당 url 을 DB 에 저장해두고 사용하는 방향으로 생각중입니다!

2024-07-17 02:32 UTC, JGoo99 commented
## #️⃣연관된 이슈

> ex) #이슈번호, #이슈번호

#17 
#21 

<br/>

## 📝작업 내용

객체 파일을 생성할 때 사용한 key 값을 별도로 저장하지 않고 객체 URL 에서 key 값을 가져와 해당 파일을 삭제합니다.

- DB 필드는 이미지 URL 만 유지하면 됨. (키값을 저장할 필요x)

- S3Uri 를 활용하면 객체 URL 을 디코딩하여 key 값을 쉽게 가져올 수 있습니다. (이슈 해결)

<br/>

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

pr 볼륨이 너무 커진 느낌이 있어 죄송합니다ㅜㅜ
단순 궁금증을 포함해서 수정 제안 모두 환영이니 정말 부담없이 코맨트 남겨주세요!!!

2024-07-17 05:50 UTC, rlagkswn00 approved these changes
고생하셨습니다!

2024-07-17 11:07 UTC, junyoungBae1 approved these changes
잘 작성하신 것 같습니다...!

2024-07-17 11:21 UTC, merged