Kakao login
KUIT-AGARANG/Agarang-Backend pull request #22
Opened 2024-07-17 06:12 UTC by AppleMint98

## #️⃣연관된 이슈

> #15 

## 📝작업 내용

> 카카오 OAuth2 로그인 구현, JWT 토큰 발행

- http://localhost:8080/api/auth/oauth2/kakao URL로 접근 시 소셜로그인이 가능합니다.
- Response 패키지는 KUIT3_Server 레포에서 가져왔습니다
- Member 엔티티에 oauthId 필드를 추가했는데, kakao_ , google_ 등 Auth Server를 표시하기 위해 넣었습니다.. 의견부탁드립니다!
- Jwt 토큰 발행 후 redirecturl 에 넣어서 반환하도록 되어있습니다.  

### 스크린샷 (선택)

>  이런식으로 들어갑니다! 아직 `save()` 만 있습니다 -> 추후 컨트롤러 구현할 때 보완하겠습니다. 
![image](https://github.com/user-attachments/assets/68f44f02-43ce-44ed-9369-e8f4fd1177d4)

## 💬리뷰 요구사항(선택)

- oauthId 필드를 추가해도 될 지 의견부탁드립니다!
- login관련 패키지를 domain에 두어도 될까요

2024-07-17 06:25 UTC, rlagkswn00 requested changes
고생하셨습니다!
yml내 보안조치 필요한 내용들 제외해주시고 나머지는 확인만 해주시면 될거같습니다!

2024-07-17 06:25 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/login/handler/OAuth2SuccessHandler.java
> +  public void onAuthenticationSuccess(
불-편

2024-07-17 06:25 UTC, rlagkswn00 commented on src/main/resources/application.yml
> +  jwt-expired-in: 3600000  # 1시간
숨겨주세요....

2024-07-17 06:25 UTC, rlagkswn00 commented on src/main/resources/application.yml
> +
이것두.. 숨겨주세요...

2024-07-17 06:25 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/global/common/response/status/ResponseStatus.java
> +}
이건 PR 머지하고 나시면 리팩토링해서 올려두겠슴니당

2024-07-17 06:25 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/global/common/exception/jwt/bad_request/JwtBadRequestException.java
> +
`ControllerAdvice` 사용해서 `ExceptionHandler` 추후에 리팩토링 해주시면 좋을거 같습니당

2024-07-17 11:16 UTC, JGoo99 requested changes
인증, 인가 파트는 항상 어려운 것 같아요...ㅎ
yml 파일 설정, 로그인 테스트만 잘 되면 좋을 것 같습니다!!

2024-07-17 11:16 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/login/handler/OAuth2SuccessHandler.java
> +    response.sendRedirect("http://localhost:8080/auth/oauth-response/" + token + "/3600"); // 3600초
url 은 yml 파일의 변수로 빼서 `배포용 서버 url`, `개발용 로컬 url` 따로 관리하면 편할 것 같아요!

2024-07-17 11:16 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/login/service/LoginService.java
> +    // TODO: Google 로그인 추가
소셜 도메인(kakao, google) 정보를 담는 enum 만들어서 관리하면 하드코딩을 방지할 수 있을 것 같아요!

2024-07-17 11:16 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/login/util/JwtProvider.java
> +    Date validity = new Date(now.getTime() + JWT_EXPIRED_IN);
```suggestion
Date validity = new Date(System.currentTimeMillis() + JWT_EXPIRED_IN);
```
이런 방법도 있어요! 취향차이인 것 같습니다!ㅎㅎ

2024-07-17 11:16 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/login/service/LoginService.java
> +    memberRepository.save(member);
회의 때 이야기 해주신대로 이부분 if 문으로 감싸서 중복 저장 방지하는 것으로 이해했습니다!

2024-07-17 11:16 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/login/util/JwtProvider.java
> +        .claim("userId", userId)
```java
Claims claims = Jwts.claims();
claims.put("userId", userId);
```
이렇게 하면 setClaims 에 한번에 넣을 수 있어요! 이것도 취향차이인 것 같습니다ㅎ

2024-07-17 11:16 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/global/common/config/SecurityConfig.java
> +            .anyRequest().permitAll()
```java
.requestMatchers("/ex").hasRole("member")
.anyRequest().permitAll()
```
이부분은 로그인 테스트용 엔드포인트 만들어서 머지하기 전에 오류없는지, 로그인화면으로 리다이렉트 되는지 등등 테스트해보면 좋을 것 같아요!

2024-07-17 11:16 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/global/common/config/SecurityConfig.java
> +            .redirectionEndpoint(endpoint -> endpoint.baseUri("/oauth2/callback/*"))
yml 에 설정해둔 것 외에도 config 에도 별도로 명시해야하나요??

2024-07-17 11:16 UTC, JGoo99 commented on src/main/resources/application.yml
> +  jwt-expired-in: 3600000  # 1시간
노션에 공유된 secret 파일에 붙여넣고 base64 로 인코딩한 문자열을 git secrets 에서 업데이트하면 됩니다!
(APPLICATION_SECRET 변수를 수정하면 됩니다.)

[참고 링크](https://developing-mango.tistory.com/65)

근데 탭키나 스페이스바 들어가면 빌드 실패떠서 확인 꼭 해주세요!

2024-07-18 03:19 UTC, applemint98 commented on src/main/java/com/kuit/agarang/domain/login/handler/OAuth2SuccessHandler.java
> +  public void onAuthenticationSuccess(
바로고치겠습니다 ㅜㅜ

2024-07-18 03:19 UTC, applemint98 commented on src/main/java/com/kuit/agarang/domain/login/util/JwtProvider.java
> +        .claim("userId", userId)
질문 있습니다!
setClaims에 한번에 넣을 수 있다는게,
```
claims.put("userId", userId) 
```
이걸 추가하면 

```
.claim("userId", userId) 
```

를 대체할 수 있다는 뜻인가용??

2024-07-18 03:19 UTC, applemint98 commented on src/main/java/com/kuit/agarang/global/common/config/SecurityConfig.java
> +            .anyRequest().permitAll()
좋아요! 테스트코드도 한번 짜보겠습니다!

2024-07-18 03:19 UTC, AppleMint98 commented on src/main/java/com/kuit/agarang/global/common/config/SecurityConfig.java
> +            .redirectionEndpoint(endpoint -> endpoint.baseUri("/oauth2/callback/*"))
Config에서 따로 명시한 이유는, SpringSecurity에서 설정한 기본값을 사용하지 않을 때 입니다! 
(Kakao Developers에 등록한 url)

별도의 커스터마이징이 필요하면,  ex) 사용자 역할 별 다른 리디렉션 url 
config 파일이 우선권을 가지기 때문에, 별도로 설정해주면 된다고 합니다!! 

저희는 따로 설정이 필요하지 않을 것 같아요.. 빼도 될 것 같습니다 감사합니다!!

접근 url은 http://localhost:8080/oauth2/authorization/kakao
redirection url은 http://localhost:8080/oauth2/callback/kakao

이렇게 설정됩니당

2024-07-18 03:19 UTC, AppleMint98 commented on src/main/java/com/kuit/agarang/global/common/exception/jwt/bad_request/JwtBadRequestException.java
> +
넵 확인했습니다!

2024-07-18 03:19 UTC, AppleMint98 commented on src/main/resources/application.yml
> +  jwt-expired-in: 3600000  # 1시간
넵 확인했습니다!
올라간 키값들은 전부 재발급했습니다

2024-07-18 15:02 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/login/util/JwtProvider.java
> +        .claim("userId", userId)
직관적으로는 그렇게 이해가 되는데, 한 번 테스트해보면 좋을 것 같아요!

2024-07-19 08:58 UTC, rlagkswn00 approved these changes
LGTM!

2024-07-20 19:04 UTC, junyoungBae1 approved these changes
OAuth 로그인 구현에 대해서 많이 궁금했는데, 덕분에 많이 알게 된 것 같습니다.

OAuth2SuccessHandler 클래스에서 JWT 토큰을 생성하고 리다이렉트하는 로직이 깔끔하네요.

만약 일반 로그인도 추가하게 된다 해도 금방 될 것 같아요 :)
고생하셨습니다.

2024-07-20 21:55 UTC, JGoo99 approved these changes
로그만 지우고 바로 머지해도 될 것 같아요!! 수고하셨습니다ㅎㅎ

2024-07-20 21:55 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/login/util/JwtProvider.java
>      log.info("JWT key={}", JWT_SECRET_KEY);
이 로그는 지워도 좋을 것 같아요!!

2024-07-22 03:32 UTC, merged