[Feature] 다이어리 탭 조회 기능 구현
KUIT-AGARANG/Agarang-Backend pull request #23
Opened 2024-07-17 08:56 UTC by rlagkswn00

## #️⃣연관된 이슈

> #5 

## 📝작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

### ✅다이어리 조회 기능 구현
총 네가지의 endpoint 제작했습니다.
모든 경로는 동일하며, querString을 기반으로 구분됩니다.
같은 메모리 조회인데 queryString에서 `viewType`에 따라 달라지도록 구현했습니다.

추후 페이징 처리를 위해 DTO에 **page**와 **size**가 추가되어 있습니다.

#### 1. 다이어리 카드 
- 다이어리 카드 건별로 조회할 수 잇습니다.
- 상단의 이미지를 출력하기 위한 썸네일 정보가 포함되어 있습니다.
- 일 단위로 한 아기에게 작성된 다이어리 목록이 모두 출력됩니다.
- 정렬은 최신순입니다.

#### 2. 즐겨찾기 탭 조회
- 즐겨찾기 탭 조회 시 사용자에게 설정된 아기의 다이어리 중 즐겨찾기를 한 정보들이 출력됩니다.
- 작성자가 누구든 상관없이 아기의 다이어리 중 즐겨찾기 되어있다면 모두 조회합니다.

#### 3. 월 탭 조회
- 월별로 하나의 이미지를 출력하도록 하였습니다.
- 월별로 가장 최신의 이미지를 출력합니다.

#### 4. 일 탭 조회
- 아기의 모든 다이어리를 출력합니다.

### ✅그 외

1. DateUtil 클래스의 추가
- 날짜 포맷팅을 비롯한 처리가 많을 것으로 예상되어 분리하였습니다.

3. ViewType Enum 클래스의 추가
- 경로가 같아 viewType으로 구분하기 위해 Enum 클래스로 관리합니다.

> 구체적인 내용은 API 명세서 확인 부탁드립니다!

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

1. viewType 분기
- 현재 분기가 if문을 기반으로 이루어집니다. 조금더 효율적인 구조가 떠오르지 않는데 한번 살펴봐주시면 감사드리겠습니다.

**나머지 부분에서 질문이나 코멘트 있으시면 편하게 남겨주세욥!(오랜만에 짜니까 좀 부족한게 많이 보이네요)😂**

2024-07-17 08:58 UTC, rlagkswn00 commented
추가로, @AppleMint98 님께서 올린 PR과 충돌될걸로 예상됩니다! 
먼저 머지하시면 제가 마무리지어서 올릴게요!

2024-07-17 14:15 UTC, JGoo99 requested changes
리뷰하면서 더 많이 배우기만 하고 가네요! 특히 DateUtil 분리한 것과 리포지토리 쿼리를 인상깊게 봤습니다.
코멘트 몇가지만 수정해주시면 감사드립니당!!

2024-07-17 14:15 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/memory/enums/ViewType.java
> +  }
항상 static hashmap 에 미리 넣어두고 get() 으로 가져오는 방법을 주로 사용했는데,
이런 방법도 있네요! 좋은 정보 알아갑니다!

2024-07-17 14:15 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/memory/repository/MemoryRepository.java
> +  List<Object[]> findByMemoriesByDateAndBabyOrdeOrderByCreatedAtDesc(LocalDate date, Baby baby);
오타확인 부탁드립니다! (Orde)

2024-07-17 14:15 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/memory/controller/MemoryController.java
> +    throw new RuntimeException();
Result 가 제너릭이니까 Object response 를 선언해두고 각 if 문 안에서 response 값을 넣는 건 어떤가요?
그럼 마지막에만 리턴하면 돼서 코드중복을 피할 수 있어요.

추가로, viewType 에 우선순위가 있는게 아니니까 switch 문을 사용해보는 건 어떨까요?
if 문은 위에서부터 차례대로 조건문을 검사하는 반면 (최악 O(n)), switch 는 바로 매핑(O(1))되는 장점이 있습니다!
만약 switch 문이면 default 로 에러처리를 하면 될 것 같아요!

저도 개발하면서 switch 문은 잘 사용해보지 않아서 이 컨트롤러에서 고민을 많이 해봤는데, 어떤식으로든 if 문의 개선이 들어간다면 더 좋은 코드가 될 수 있을 것 같아요!

2024-07-17 14:15 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/memory/enums/ViewType.java
> +  FAVORITE("favorite"),
여기서 favorite 이 bookmark 의 의미인가요?
만약 맞다면 다른 로직을 포함해서 둘 중 하나로 통일하면 의미에 혼동이 없을 것 같아요!

2024-07-17 14:15 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryDTO.java
> +  private String Date;
특별한 이유가 없다면 소문자로 바꾸는 것이 좋을 것 같습니다!

2024-07-17 14:15 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/memory/repository/MemoryRepository.java
> +public interface MemoryRepository extends JpaRepository<Memory,Long> {
JpaRepository 는 @Repository 를 선언하지 않아도 자동으로 등록된다고 알고있습니다.
(가독성을 위해 추가하는 경우도 존재하니 취향따라...ㅎㅎ)

Memory 랑 Long 사이에 스페이스바 하나만 눌러주시겠어요?..ㅋㅋㅋㅋ

2024-07-17 14:15 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
> +            .toList();
리포지토리에서 가져오는 메서드 이름 자체도 길고, 변환 작업도 배열로 이루어지기 때문에
별도 메서드로 분리해서 네이밍을 주면 가독성 높이는데에 도움이 될 것 같아요!

2024-07-17 14:15 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
> +    List<String> imageUrlsByDate = memoryRepository.findImageUrlsByDate(startDate, endDate);
이 부분도 별도 메서드로 분리하거나, 상수값을 final 변수로 주면 어떨까요?

2024-07-17 14:15 UTC, korogoo commented on src/test/java/com/kuit/agarang/domain/memory/repository/MemoryRepositoryTest.java
> +    System.out.println(memories);
임시 테스트인 것은 알지만 sout 사용은 지양하고싶어 코맨트 남깁니다!

2024-07-17 14:15 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryImageDTO.java
> +  @Builder
지우기 한 번만...너무 멀어보이네요..

2024-07-17 14:24 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/memory/repository/MemoryRepository.java
> +public interface MemoryRepository extends JpaRepository<Memory,Long> {
습관 + 취향이긴 했습니당
우리 모두 다같이 코드 한줄 줄이는 걸로 하죵!

2024-07-17 14:26 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
> +            .toList();
공감합니당 안그래도 작성하면서 너무 냄새난다 생각했는데...
메서드명을 어떻게 하면좋을지도 고민해봐야겠네영

2024-07-17 14:54 UTC, rlagkswn00 commented
1. 자잘한 오타수정 완료했습니다!
2. 메소드 분리 두가지 진행하였고, DTO를 적용하여 불분명한 Object를 사용하지 않도록 했습니다!

2024-07-17 15:22 UTC, JGoo99 requested changes
찐찐막 리뷰입니다!

2024-07-17 15:22 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/memory/model/dto/MonthlyMemoryDTO.java
> +}
서비스에서 AllArgsConstructor 를 사용하고 있는 객체인데, 같은 String 값이라서 약간 위험해보입니다...!!

2024-07-17 15:22 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/memory/model/dto/DailyMemoryRequest.java
> +@Setter
이 dto 는 어디에 사용될 예정인가요?

2024-07-17 16:10 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/memory/model/dto/DailyMemoryRequest.java
> +@Setter
헉 어쩐지.. Request가 왜 더있나.. 생각했네요...
삭제하겠습니당

2024-07-17 16:15 UTC, rlagkswn00 commented
추가 수정사항 반영하였습니다! 
확인 후 Approve 부탁드려용

2024-07-17 16:22 UTC, JGoo99 approved these changes
정말 수고 많으셨습니다!!! 👍🏼👍🏼

2024-07-19 09:17 UTC, AppleMint98 approved these changes
고생하셨습니다!! 
늦어서 미안해요 ㅠㅠ

2024-07-19 09:17 UTC, applemint98 commented on src/main/java/com/kuit/agarang/domain/baby/model/entity/Baby.java
> +    this.id = id;
Id를 생성자로 받아와야하나요 ???? 자동으로 생성되는줄 알았슴다
`@Builder`  의 Baby에도 this.id = id 로 id를 받아올까요?

2024-07-19 09:17 UTC, applemint98 commented on src/main/java/com/kuit/agarang/domain/memory/model/entity/Memory.java
> +  private List<Hashtag> hashtag;
영한이햄이 컬렉션은 필드에서 바로 초기화하라고 했던게 기억에남아서 올립니다!
```
private List<Hashtag> hashtag = new ArrayList<>()   
```
이런식으로요!

이유는 
1. NPE 에 안전하고
2. JPA에서 하이버네이트 별도의 내장 컬렉션으로 변경하기 때문에, 
ex)class org.hibernate.collection.internal.PersistentBag
추후 컬렉션을 생성할 때 문제가 생길 수 도 있다고 합니다!

또 이거는 제 의문점인데

그냥 ArrayList 쓰면 동시성 문제에서 안전하지 않다고 해서 
CuncurrnetList 쓰라고 했던 기억이 나서 관련 링크 첨부하겠습니다!
https://coding-business.tistory.com/22

제가 틀린거 있으면 편하게 알려주세요!

2024-07-19 09:17 UTC, applemint98 commented on src/main/java/com/kuit/agarang/domain/memory/repository/MemoryBookmarkRepository.java
> +  @Query("SELECT m FROM MemoryBookmark mb join Memory m on m.id = mb.memory.id WHERE m.member = :member")
em.createQuery로만 배웠다가 `@Query` 가 있는줄 첨알았네요! 하나 배워갑니다!
그러면 .getResultList() 같은 메서드를 따로 쓰지 않아도 list로 반환이되나요??

2024-07-19 09:17 UTC, applemint98 commented on src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
이런 BaseResponse 부분이 충돌이 일어날것같다고 하신거죠??
저희 오류코드는 어떻게 정하나요??
4000, 4001 이렇게 천의자릿수로 정하나요아님 400, 401 등 백의자릿수로 정하나요??

2024-07-19 09:17 UTC, applemint98 commented on src/main/java/com/kuit/agarang/domain/memory/model/dto/MonthlyMemoryDTO.java
> +  }
전에 얘기해주셨던거 생각나가지고 질문이 있어서 올려봅니다!!

이게 메서드이름을 from, of, valueOf 등 다양하게 짓는데 
이펙티브자바보면 단일 파라미터일땐 from, 여러 파라미터일땐 of 라고 하던데 

다른 블로그보면 from은 다른 객체를 기반으로 DTO를 생성할 때 쓴다고 하더라고요
https://velog.io/@bluesun147/of-from-%EB%A9%94%EC%84%9C%EB%93%9C-%ED%8C%A8%ED%84%B4

이게 of, from 기준을 단순 파라미터 수로 봐야할 지, 아니면 받아오는 파라미터의 크기(단순 값을 받아오거나 객체를 받아오거나)를 기준으로 봐야할 지 궁금합니당

2024-07-19 09:17 UTC, applemint98 commented on src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryImageDTO.java
> +  }
질문이 있슴당
`@Builder` 랑 `of()` 메서드랑 둘 다 쓰는 이유가 있나요?

2024-07-19 09:17 UTC, AppleMint98 commented on src/main/java/com/kuit/agarang/domain/memory/enums/ViewType.java
> +  }
질문 있습니다!!
null값을 반환하면 MemoryController에서 RuntimeException 나가자나요
ViewType 에서 null 반환대신 예외처리를 여기서 하는거는 어떤가요??

Controller에서 하는게 더 맞는거같긴한데, 단순 궁금증때문에 질문합니다
찾아봐도 잘 안나오더라고요ㅜㅜ

2024-07-19 09:17 UTC, AppleMint98 commented on src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
WOW

2024-07-19 09:53 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/baby/model/entity/Baby.java
> +    this.id = id;
맞습니다! 다만 지금 회원쪽 기능이 구현이 안되서 로직의 구현을 위해 고정값으로 만드느라 id값 설정을 위해 임시로 만들어둔 생성자입니다! 이부분은 회원 기능 추가 후 JWT->id 조회 로직으로 변경하며 삭제될 예정입니다!

2024-07-19 09:54 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/memory/model/entity/Memory.java
> +  private List<Hashtag> hashtag;
오호.. 내부 컬렉션을 사용하는지 몰랐네요..! 
수정 후 아카이브에 조사해서 넣어두겠습니당!

+) ConcurrentList에 대해서도 동의합니당!

2024-07-19 09:56 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/memory/repository/MemoryBookmarkRepository.java
> +  @Query("SELECT m FROM MemoryBookmark mb join Memory m on m.id = mb.memory.id WHERE m.member = :member")
아마 말씀하신 부분은 JPA를 사용할 때 사용되는 키워드인듯합니다!
`@Query`는 Spring Data JPA의 기능으로 JPQL을 직접 선언하여 사용할 수 있는걸로 알고 있습니다!

2024-07-19 09:58 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
넵 맞습니다! 
이부분은 머지 후에 디코로 말씀드리겠습니다!

아마도 큰 틀이 HTTP Status인 만큼 400 500의 경우의 따라 4자리 숫자(4XXX, 5XXX)로 정하는게 좋을거 같습니다!

2024-07-19 10:01 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryImageDTO.java
> +  }
사실 빌더로 생성하고 접근제어자를 `Protected` 아래로 지정해야 조금 더 의미잇는 방식이긴 했는데, 제 의도는 다음과 같습니다!

1. 외부에서 객체를 생성할 때 직접 빌더를 사용하지 못하도록 하기 위함 파라미터 개수가 많은 Builder를 사용하다 보면 NPE에 대해 실수하기 쉬움
2. 정적 메서드를 사용할 시 생성자에 비해 의미가 명확함(여러 용도에 따라 객체 생성 메서드에 이름을 명명해서 구분할 수 있음)

2024-07-19 10:02 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/memory/enums/ViewType.java
> +  }
오! 좋은 아이디어라 생각합니다.
ControllerAdvice를 이후 PR에 반영했으니 두 PR을 머지하여 추후 수정하여 올리겠습니다!

2024-07-19 10:07 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/memory/model/dto/MonthlyMemoryDTO.java
> +  }
저는 개수로만 판단하긴 합니다!
정적 메서드가 하나만 있을 때는 of, from만으로도 충분하나 의미가 모호하긴 한거 같습니다.
다수의 정적 메서드(객체 생성 메서드)가 사용된다면 `fromMemberDTO`, `ofMemberAndBaby`등의 이름으로 짓는게 더 명확한거 같습니다.

2024-07-20 15:28 UTC, merged