[Setting] CustomException & ExceptionHandler 생성
KUIT-AGARANG/Agarang-Backend pull request #31
Opened 2024-07-18 06:15 UTC by rlagkswn00

## #️⃣연관된 이슈

> ex) #이슈번호, #이슈번호

#30 

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

## 1. Custom Exception -> `AgarangException` 생성
- 이름은 `AgarangException`으로 `RuntimeException`을 상속받습니다.
- 필드값으로 `BaseResponseStatus`를 입력받습니다(PR#23과 충돌 생길 듯하여 커밋하지 않았습니다)
- 추가적으로 `NotFoundMemberException` or `DuplicateMemberException` 등 여러 CustomException은 AgarangException을 상속받아 사용하시면 됩니다!

## 2. `RestControllerAdvice` 사용
- `@RestController`를 사용하는 모든 컨트롤러에서 발생하는 AgarangException의 경우 모두 캐치하여 예외처리 가능하도록 가장 큰 범위의 예외처리를 예시로 해놨습니다.
- 이후 만들게 되는 세세한 예외별로 제작하면 됩니다!

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

- 저번에 보여드린 템플릿으로 진행했는데 추가적으로 수정할 아이디어 주시면 반영하겠습니다!

2024-07-19 09:29 UTC, AppleMint98 approved these changes
감사합니다~!

2024-07-19 19:58 UTC, JGoo99 requested changes
### 회원 이메일 중복 예외 처리 (ex)

1) AgarangException 에 enum 을 추가해서 사용하는 방법

```java
// BaseResponseStatus
DUPLICATED_MEMBER_EXCEPTION(false, HttpStatus.BAD_REQUEST, 10001, "이메일 중복입니다.");

// service
throw new AgarangException(BaseResponseStatus.DUPLICATED_MEMBER_EXCEPTION);
```

<br/>

2) 새로운 클래스를 상속해 사용하는 방법

```java
throw new DuplicateMemberException(BaseResponseStatus.BAD_REQUEST);
```

<br/>

3) 두가지 모두 사용하는 방법

```java
throw new DuplicateMemberException(BaseResponseStatus.DUPLICATED_MEMBER_EXCEPTION);
```

<br/>

개인적으로 에러처리 방식의 자율성이 높다고 생각되는데 기존에는 어떤식으로 진행했나요???

<br/>

### 제안 합니다!

```
1. 위의 구조는 그대로 유지한다.

2. AgarangException 을 상속받은 새로운 클래스는 `BusinessException`, `InvalidValueException` 정도로 픽스한다.

3. 즉, 상황에 따른 예외를 커스텀하고 싶은 경우 클래스를 생성하지 않고 enum 을 추가한다.
```

```java
new BusinuessExeption(BaseResponseStatus.DUPLICATED_MEMBER_EXCEPTION)
```

아래는 참고했던 링크입니다. 같이 고민해봐요!!

[참고링크](https://cheese10yun.github.io/spring-guide-exception/)

<br/>

그리고 추가적으로 result 를 null 로 반환하기 보다는 빈 배열로 반환하는 것 어떤가요? 이 부분도 위 링크에 언급된 부분입니다.

null 은 의미가 불분명한 것에 반해 빈 배열은 확실히 응답 컨텐츠가 없다는 것을 명시할 수 있어요!

2024-07-21 04:15 UTC, junyoungBae1 commented
구진님 방법 좋은 것 같아요! 참고 링크 읽어 봤는데 어떤 예외가 발생했는지 더 가독성이 좋네요.

그럼 이 2개가 더 생기는 건가요?
```
public class BusinessException extends AgarangException {
    public BusinessException(BaseResponseStatus baseResponseStatus) {
        super(baseResponseStatus);
    }
}

public class InvalidValueException extends AgarangException {
    public InvalidValueException(BaseResponseStatus baseResponseStatus) {
        super(baseResponseStatus);
    }
}
```

다른 분들은 어떻게 생각하시나요?

2024-07-21 07:54 UTC, rlagkswn00 commented
@JGoo99 
3번의 경우를 생각했습니다!
그 이유로 클래스를 세부적으로 나누는 것이 서버관점에서도 정확히 어떤 에러인지 Exception 이름으로 구분 가능하기 때문이라고 생각했습니다! 그러면 예외에 대해서 정확히 어떤 예외인지 확인할 수 있기에 조치가 빠르다고 생각합니다.

그리고, enum을 추가하는건 클라이언트에 조금 더 상세한 에러를 보여줄 수 있기 때문입니다.

이외에 result에 Null값 반환보다 빈 리시트 반환이 좋다는 것에는 동의합니다! 이 부분은 반영하도록 하겠습니다!

2024-07-21 10:09 UTC, JGoo99 commented
이넘이 의미전달에 용이하다는 것에 동의합니다!

그런데 상속받은 클래스는 3-4개 정도로 한정해두고 이넘만 추가하는 구조가 개발할 때 편리하다고 생각해요.

'''java
throw new BusinessException(BaseResponseStatus.Duplicate_Member);
'''

> 개인적으로 사용법 및 예외처리의 의미가 명확하다고 생각합니다!

1. 별도의 핸들러 구현이 필요한 예외만 클래스 생성
2. 큰 의미의 클래스(비지니스) 안에서 세부적인 예외(비니지스 관련 예외)는 이넘 생성

2024-07-22 08:13 UTC, rlagkswn00 commented
아하 넵 무슨 말인지 이해했습니다!
회의때 이야기해서 정해보죠!!

2024-07-24 10:41 UTC, JGoo99 approved these changes

2024-07-24 10:41 UTC, junyoungBae1 approved these changes
LGTM 👍

2024-07-25 14:37 UTC, merged