[Feature] 플레이리스트 조회 기능 구현
KUIT-AGARANG/Agarang-Backend pull request #40
Opened 2024-07-23 17:31 UTC by junyoungBae1

## #️⃣연관된 이슈

> [#32](https://github.com/KUIT-AGARANG/Agarang-Backend/issues/32)

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

### 플레이리스트 전체 조회
- 플레이리스트 8개 전부 조회할 수 있습니다.
- /api/playlists
### 플레이리스트별 음악 조회
- 사용자에게 플레이리스트별 musicUrl이 출력됩니다.
- /api/playlists/{playlistId}/music?memberId=1

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.
- music엔 복수형이 없어서 method명을 MusicUrls로 하게 되었습니다. 차라리 songs으로 하는게 나을까요?
- 아직 예외처리는 제대로 반영이 안되어있습니다.
#### 편하게 봐주세요..!

2024-07-23 20:48 UTC, JGoo99 requested changes
> music엔 복수형이 없어서 method명을 MusicUrls로 하게 되었습니다. 차라리 songs으로 하는게 나을까요?

도메인 네이밍은 아예 고정하면 좋을 것 같아요. MusicList ...? 는 어떤가요??

너무 수고하셨습니다!!

2024-07-23 20:48 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/playlist/model/dto/PlaylistDto.java
> +    }
위에 @Builder 어노테이션을 붙이면, 외부에서 빌더로 안전하게 객체를 생성할 수 있어요!
(name 과 imageUrl 의 데이터 타입이 같기 때문에 섞일 위험 존재)

[이슈참고](https://github.com/KUIT-AGARANG/Agarang-Backend/pull/9#issuecomment-2222021653)

2024-07-23 20:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/playlist/model/dto/PlaylistsResponse.java
> +}
`playlists` 필드가 하나뿐이라면 `PlaylistsResponse` 를 따로 생성하지말고,
`List<PlaylistDto>` 로 반환해도 될 것 같은데 
혹시 Dto 를 다시 클래스로 감싼 다른 이유가 있었나요? (다른 response 클래스도 이렇게 설계하신 이유가 궁금합니다!)

혹시 네이밍 때문이라면 `List<PlaylistResponse>` 도 괜찮을 것 같아요.

2024-07-23 20:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +    }
```suggestion
public List<PlaylistDto> getAllPlaylists() {
    List<Playlist> playlists = playlistRepository.findAll();
    return playlists.stream().map(PlaylistDto::from).toList();
}
```

PlaylistDto 클래스에서 static 메서드로 form 을 생성하고, 반환 값을 List 로 둔다면 이런 코드도 가능합니다.

PlaylistDto.java

```java
public class PlaylistDto {
    private Long id;
    private String name;
    private String imageUrl;

    @Builder
    public PlaylistDto(Long id, String name, String imageUrl) {
        this.id = id;
        this.name = name;
        this.imageUrl = imageUrl;
    }

    public static PlaylistDto from(Playlist playlist) {
        return PlaylistDto.builder()
          .id(playlist.getId())
          .name(playlist.getName())
          .imageUrl(playlist.getImageUrl())
          .build();
    }
}
```

2024-07-23 20:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/playlist/model/dto/MusicUrlsResponse.java
> +}
이 부분도 특별히 dto 로 한번 더 감싸지 않아도 된다면 `List<MusicDto>`  등의 형태로 반환하면 될 것 같아요.

그리고 MusicDto 의 필드로 url 외의 음악에 대한 더 자세한 정보 넘겨줘도 좋을 것 같습니다!

2024-07-23 20:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +    }
리펙토링 때 전체적으로 페이징 처리가 들어가면 좋을 것 같아요.

저희 서비스가 아직 개발단계라서 findAll 처리 시 많은 양의 데이터를 가져온다해도 시간이 많이 걸리는 것에 그치겠지만,
서비스가 크다고 가정하면 서버에 큰 부하를 가져올 수 있다네요..!

2024-07-23 20:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/playlist/controller/PlaylistController.java
> +    public ResponseEntity<BaseResponse> getMusicUrlsByPlaylistId(@PathVariable Long id, @RequestParam Long memberId) {
인가 처리 방식에 따라 달라지겠지만 프론트 측에서 RequestParam 으로 memberId 를 직접 전달해주지 않아도 서버 내에서 다른 어노테이션으로 회원 정보를 받을 수 있어요! (ex. `@AuthenticationPrincipal`, ...)

2024-07-23 20:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/playlist/controller/PlaylistController.java
> +    public ResponseEntity<BaseResponse> getMusicUrlsByPlaylistId(@PathVariable Long id, @RequestParam Long memberId) {
playlist 한 개에 대한 정보를 조회하는 쿼리가 필요하지 않다면, 엔드포인트 두개를 합치는 건 어떨까요?

```
GET /api/playlists/1
```
개인적으로 해당 `플레이리스트에 대한 정보`와 함께 안에 담겨있는 `음악들에 대한 정보도` 반환할 것이라고 예상되는 uri 인 것 같아요!

혹시 몰라서 멜론도 찾아봤는데 플레이리스트 전체를 불러오는 것 외에 개별 플레이리스트(음악 정보 제외)에 대한 정보를 불러오는 엔드포인트는 뭔가 없는 것 같..! 습니다.

2024-07-23 20:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/playlist/repository/MemoryPlaylistRepository.java
> +@Repository
요것은 없어도 될 것 같슴다!

2024-07-24 08:19 UTC, rlagkswn00 requested changes
고생하셨습니다!
여러모로 처음이라 어려울텐데 오늘 회의랑 토요일에 만나서 한번 더 이야기 해봐용
리뷰 확인해주세용

2024-07-24 08:19 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/playlist/controller/PlaylistController.java
> +    public ResponseEntity<BaseResponse> getMusicUrlsByPlaylistId(@PathVariable Long id, @RequestParam Long memberId) {
비슷한 의견인데, `/api/playlists/{playlistId}` 의 경우 명확하게 "특정 플레이리스트 내용 전체 조회"로 이해했는데, `/music`이 붙은 이 API는 어떤걸 의미하는지 조금 파악하기 어렵습니다.
혹시 다른 용도가 있다면 말씀해주세요!

2024-07-24 08:19 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +public class PlaylistService {
어노테이션 추가로 Transaction처리가 필요해보입니다.
아래 링크 한번 참고하셔서 추가해보시면 좋을거 같습니다!

[관련 링크](https://medium.com/gdgsongdo/transactional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%95%8C%EA%B3%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-7b0105eb5ed6)

2024-07-24 08:19 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +                .orElseThrow(() -> new RuntimeException("Playlist not found"));
좋은 투두 주석이라 생각합니당 ㅎㅅㅎ

2024-07-24 08:19 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/playlist/model/dto/PlaylistResponse.java
> +}
이 내용과 `PlaylistsResponse`와 이름이 너무 불분명하고 s하나 차이라서 나중에 다시 보면 헷갈리기 좋을거 같아서 정확하게 목적이 명시된 이름으로 수정이 필요할거 같습니다.

2024-07-24 08:19 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +        List<Memory> memories = memoryRepository.findAllById(memoryIds);
오 이렇게 하면 ID 리스트의 값들이 쿼리문 Where절에 OR로 들어가나요?

2024-07-24 08:19 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +    }
데이터가 조금 부족한거 같습니다!
주소만 넘어가는 것이 아닌, 음악 대표이미지, 플레이리스트 대표 이미지, 찜여부 정도의 정보가 더 필요한거 같아요!
화면상에서 음악url만 필요한 API보다 추가 내용이 더 필요한 API가 사용될거 같습니다!

2024-07-24 09:17 UTC, AppleMint98 reviewed
고생하셨습니다 !!

2024-07-24 09:17 UTC, AppleMint98 commented on src/main/java/com/kuit/agarang/domain/playlist/controller/PlaylistController.java
> +    public ResponseEntity<BaseResponse> getMusicUrlsByPlaylistId(@PathVariable Long id, @RequestParam Long memberId) {
질문 있습니다!

홈 화면에서 음악 재생할 때, >> 나 << 버튼을 통해 다음 곡 혹은 이전 곡을 재생하는 기준은 어떻게 되나요?
만약 단일 플레이리스트 내에서 음악을 바꾼다면 단일 플레이리스트를 조회하는 API가 필요할것 같아서요!

아니면 홈 API에서 따로 만들어야할까요??

2024-07-24 09:17 UTC, AppleMint98 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +public class PlaylistService {
맞습니다!
읽기전용이라면
```
@Transactional(readOnly = true) 
```
어노테이션이 필요할것 같슴다

2024-07-24 09:17 UTC, AppleMint98 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +    }
저희 플레이리스트 조회는 무한스크롤 방식으로 하나요?

2024-07-24 11:42 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/model/dto/PlaylistDto.java
> +    }
좋은 지적 감사합니다! @Builder 어노테이션을 추가해서 빌더 패턴을 적용하겠습니다!

2024-07-24 12:00 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/model/dto/PlaylistsResponse.java
> +}
그 플레이리스트는 8개 고정이라 딱히 추가할 것이 없을 것 같긴 합니다.

Response, Request에 관해서 만들어 놓는게 가독성이 좋을 것 같고,
한주님 코드를 참조하면서 해서 일관성있게 설계하려고 했습니다.

그래서 객체를 따로 정의하는 것이 좋겠다고 판단했습니다!

2024-07-24 12:02 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/model/dto/MusicUrlsResponse.java
> +}
Url만 보내는게 이상하긴 하네요.
MusicUrlsResponse를 MusicListResponse로 변경하고,
정보를 추가하도록 하겠습니다.

2024-07-24 13:08 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +    }
@JGoo99 
좋은 지적 감사합니다. 페이징은 리팩토링 때 적용해보기로 하고 , findAll 처리 성능 개선에 대해서 고민해보겠습니다! 

@AppleMint98 
일정 단위로 데이터를 나누어서 조회하게 되면은 플레이리스트 전체 듣기를 하고 있을 때, 
필요한 시점에 다음 데이터를 가져오게 하는 것에 대한 고민이 필요할 것 같습니다!
다른 앱들 재생목록 보면 한번에 다 조회하는 것 같긴 합니다!
고민을 좀 더 해보겠습니다!

2024-07-24 13:12 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/controller/PlaylistController.java
> +    public ResponseEntity<BaseResponse> getMusicUrlsByPlaylistId(@PathVariable Long id, @RequestParam Long memberId) {
인가 처리 방식을 아직 확실하게는 몰라서 일단 RequestParam으로 memberId를 받도록 했습니다. 
 말씀하신 대로, 인가 처리 방식이 정해지면 @AuthenticationPrincipal 등의 어노테이션을 사용하여 서버 내에서 회원 정보를 받을 수 있도록 수정하겠습니다!

2024-07-24 13:19 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/controller/PlaylistController.java
> +    public ResponseEntity<BaseResponse> getMusicUrlsByPlaylistId(@PathVariable Long id, @RequestParam Long memberId) {
회의 때 이야기한 것 처럼 지우도록 하겠습니다..! 혼란을 드려 죄송합니다 😢

@AppleMint98 
홈 API에서 따로 만들 필요는 없을 것 같습니다! 아마 클라이언트쪽에 캐싱처리하거나, 관련 API 호출은 playlist쪽에서 처리하지 않을까 싶습니다.

2024-07-24 13:21 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/repository/MemoryPlaylistRepository.java
> +@Repository
앗! 감사합니다!

2024-07-24 13:23 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +public class PlaylistService {
관련 링크까지..! 공부하고 수정하도록 하겠습니다! 감사합니다.

2024-07-24 13:35 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +        List<Memory> memories = memoryRepository.findAllById(memoryIds);
findAllById 메서드에서 전달된 ID 리스트의 값들이 IN절에 포함됩니다.
```
SELECT * FROM memory WHERE id IN (1, 2, 3, ...);
```
OR과 같은 결과값을 출력하지만 성능에는 차이가 있다고 하네요!
[관련링크](https://i-hope9.github.io/posts_til/2021-04-24-TIL-DB.html)

2024-07-24 16:19 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/playlist/model/dto/PlaylistsResponse.java
> +}
처음에는 FE 쪽에서 데이터 읽어올 때 
`result -> 진짜 원하는 데이터` 가 아닌,
`result -> playlists -> 진짜 원하는 데이터` 이런식으로 한 단계 더 들어가야해서 불편하지 않을까? 싶었는데,
나중에 페이징 처리 이후 다른 필드 추가되면 오히려 가독성이 좋겠네요.

전체 통일해서 하면 일관성있으니 저도 통일해서 사용하겠습니다!

2024-07-24 16:22 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +    }
플레이리스트에 추가할 수 있는 곡 수를 제한해둔다면 전체를 불러오는 방식도 안전할 것 같아요...! 원래는 어떤식으로 하는지 궁금하네요.

2024-07-27 09:36 UTC, junyoungBae1 commented
## 수정사항

### Entity
- memory에 musicTitle 추가

### 플레이스트별 조회 관련
- musicUrl만 조회 -> playlistDto,musicDto 조회
- 해쉬태그 추가 ( pm님이 명사가 너무 많다고 일단 보류하자해서 #mood만)
- 북마크 추가

### Service
- getPlaylist 제거
- getMusicUrl -> getPlaylistTracks으로 변경 및 DB 조회 로직 변경

2024-07-29 11:10 UTC, JGoo99 approved these changes
수고하셨습니다!!

2024-07-29 11:10 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +        return musicBookmark != null;
데이터의 유무만 체크하는 거면 existsByMemoryIdAndMemberId 도 괜찮을 것 같아요!

2024-07-29 14:16 UTC, rlagkswn00 approved these changes
고생하셨습니다!

2024-07-30 11:50 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +        return musicBookmark != null;
수정하였습니다! 감사합니다!

2024-07-30 11:50 UTC, merged