Sign with
KUIT-AGARANG/Agarang-Backend pull request #52
Opened 2024-07-27 00:57 UTC by AppleMint98

## #️⃣연관된 이슈

> ex) #48

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
-  기존 소셜 로그인 (Access Token 발급 과정) 리팩토링
-  토큰을 통한 유저 정보 요청
-  Refresh Token 구현

### 스크린샷 (선택)

> 기본 로그인 화면, 각 버튼 클릭 시 해당 소셜로그인 페이지로 이동 
![image](https://github.com/user-attachments/assets/df1e2bfb-552d-4e42-8523-1a363a6b483f)

> Member 테이블
![image](https://github.com/user-attachments/assets/d7643aa4-2a53-4b98-af74-db02dee1ec51)

> RefreshToken 테이블
![image](https://github.com/user-attachments/assets/0fac9591-e994-4234-a719-4b26f9890a5c)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

- 기존 role 필드가 , 추후 인가 단계에서 사용되는 필드의 이름이랑 헷갈릴 수 있어서
("ROLE_USER", "ROLE_ADMIN" 등 )가족 내 역할을 familyRole 필드로 따로 추가하였습니다 

- 현재 MemberRepository에 유저 저장 시 RefreshToken과 연결되지 않아서 추후 수정하겠습니다
(각각 독립적인 테이블처럼 들어갑니다)

2024-07-27 00:59 UTC, AppleMint98 commented
SecurityConfig.java 파일에서 충돌이나네요ㅠㅠ
별 내용은 아닌거같아서 추후 수정하겠습니다

2024-07-27 10:04 UTC, JGoo99 requested changes
reissue 컨트롤러 부분만 리펙토링 마치면 깔끔한 코드가 될 것 같아요!! 수고하셨습니다!

2024-07-27 10:04 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/login/controller/ReissueController.java
> +  public ResponseEntity<?> reissue(HttpServletRequest request, HttpServletResponse response) {
```suggestion
  public ResponseEntity<BaseResponse<ResponseDto>> reissue(HttpServletRequest request, HttpServletResponse response) {
```

와일드 카드로 처리하기 보다는 확실히 응답형태를 지정해주면 좋을 것 같아요!

2024-07-27 10:04 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/login/controller/ReissueController.java
> +    }
개인적으로 예외처리는 `throw new CustomException(...)` 으로 처리하면 직관적으로 이해하기 좋을 것 같아요!
서비스단으로 분리해서 예외처리 하는 것을 추천합니다!!

2024-07-27 10:04 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/login/controller/ReissueController.java
> +  }
위에 쿠키관련 로직포함해서 CookieUtil 로 분리해도 관리하기 편할 것 같습니다!

2024-07-27 10:04 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/login/handler/CustomSuccessHandler.java
> +    response.sendRedirect("http://localhost:8080/"); // 성공 시 redirect url
develop 최신 버전 당겨오면 system 환경변수로 `@Value("${app.baseUrl})` ("https://agarang.site") 혹은 로컬 url 로 설정되어있는 것 사용할 수 있어요!

2024-07-27 10:04 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/login/handler/CustomSuccessHandler.java
> +    refreshRepository.save(refreshToken);
나중에 오래된 refreshToken 은 정리할 필요가 있어보입니다!

2024-07-27 10:04 UTC, korogoo commented on src/main/java/com/kuit/agarang/domain/login/jwt/JWTFilter.java
> +    if (accessToken == null) {
쿠키에 담긴 토큰은 프론트측에서 넣거나 뺄 수 없는데, 토큰의 유무로 판단해도 permitAll 인지 아닌지 구별이 되나요???

2024-07-27 10:04 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/login/controller/ReissueController.java
> +    response.setHeader("access", newAccess);
액세스토큰도 쿠키에 넣는건 어떤가요??
그리고 jwt 토큰은 통상적으로 Authorization 을 사용하는데 access 를 키로 사용한 이유가 궁금합니다!

2024-07-27 15:50 UTC, rlagkswn00 approved these changes
고생하셨습니당
몇가지 확인만 해주세용

2024-07-27 15:50 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/member/repository/RefreshRepository.java
> +  @Transactional
Repository에 Transactional 어노테이션 사용하지 않는다는 내용이 정리되어 있어서 관련 링크 남겨드립니당!
[관련 링크](https://www.inflearn.com/community/questions/272147/repository%EC%9D%80-%ED%8A%B8%EB%9E%9C%EC%A0%9D%EC%85%98%EC%9D%B4-%EA%B8%B0%EB%B3%B8%EC%9D%B8%EA%B0%80%EC%9A%94)

2024-07-27 15:50 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/login/service/CustomOAuth2UserService.java
> +      memberDTO.setRole(existData.getRole());
Setter로 하는거보다 생성자 or 메서드를 사용하는게 중복을 줄여줄거 같습니당

2024-07-27 15:50 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/login/service/CustomOAuth2UserService.java
> +    if (existData == null) {
Optional처리하면 조금 더 편할거같습니당

2024-07-27 18:22 UTC, junyoungBae1 approved these changes
고생하셨습니다!

인가 처리에 대해 많이 알게 된 것 같습니다.

2024-07-27 18:22 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/login/controller/ReissueController.java
> +    }
request.getCookies()로 cookies을 받아오는데 쿠키가 없을 경우도 있나요?
있다면 cookie에 대한 예외처리도 필요있지 않을까 싶습니다.
```
 Cookie[] cookies = request.getCookies();
    for (Cookie cookie : cookies) {
      if (cookie.getName().equals("refresh")) {
        refresh = cookie.getValue();
      }
    }
```

2024-07-30 23:35 UTC, AppleMint98 commented on src/main/java/com/kuit/agarang/domain/login/controller/ReissueController.java
> +  public ResponseEntity<?> reissue(HttpServletRequest request, HttpServletResponse response) {
확인했습니다!!

2024-07-31 01:38 UTC, AppleMint98 commented
기존 BaseResponse는 미션에 있던 코드를 가져와서 사용했는데
저희 코드가 따로 있고, 더이상 사용하지 않는 코드이기 때문에 삭제했습니다! 

기존 코드에 Comment 남겨주신것 위주로 수정했습니다!

1. ResponseEntity<BaseResponse<ReissueDto>>
ReissueDto : accessToken, refreshToken, providerId, role 을 받는 Dto를 생성해서 응답하였습니다.

2. JWT Service 클래스 
기존 ReissueController가 예외처리 까지 진행하였는데, JWT Service를 새로 생성해서 
Token Reissue 하는 로직및 예외처리를 분리했습니다 

3. CookieUtil, AuthenticationUtil,
쿠키 생성 로직과 세션에서 유저의 ProviderId와 Role을 가져오는 로직을 따로 분리했습니다

4. 기타 수정사항
- jwt 토큰의 헤더를 Authorization로 변경하였습니다
- Repository의 Transactional  어노테이션을 Service 계층으로 분리하였습니다. 
- Setter로 생성하던 DTO들을 별도의 메서드 of() 를 사용하여 처리하였습니다. 
- Optional 처리를 통해 Member의 null 값 확인 코드를 수정하였습니다 .
- public static 메서드 -> `@Component` 로 빈 등록하여 사용하는 것으로 수정하였습니다.

5. TODO
- 예외처리의 세분화가 필요합니다. 일단 throw new AgarangException(BAD_REQUEST) 으로 통일하였는데,
추후 세부 예외코드의 추가가 필요합니다. 
- 쿠키 처리 등 예외처리를 더 추가해야 합니다

2024-07-31 09:58 UTC, JGoo99 approved these changes
코드가 정말 깔끔해졌어요...!!!! 수고 많으셨습니다!

2024-07-31 23:35 UTC, merged