[Feature] 로그인 과정 API구현
KUIT-AGARANG/Agarang-Backend pull request #54
Opened 2024-07-27 12:27 UTC by AppleMint98

## #️⃣연관된 이슈

> #36 

## 📝작업 내용

> 로그인 과정 API 4개 등록
- 아기 코드 등록 
- 가족 역할 등록 
- 태명 등록
- 출산예정일 등록

### 스크린샷 (선택)

- KAKAO 아이디로 테스트했습니다. 

- 아기 코드 등록 -> 
    - 아기 코드가 있으면 Member와 Baby 연결 (BabyCode 로직은 추후 구현, 일단 Id값으로) , FamilyRole 설정
    - 아기 코드가 없을 시 태명 및 출산예정일로 Baby 생성, FamilyRole 설정

![image](https://github.com/user-attachments/assets/37492098-a018-4452-8b9a-1bb5afc9ac94)

- 아기 태명 및 출산예정일 등록

![image](https://github.com/user-attachments/assets/692b9e4a-3271-45f4-8f5d-1a891015d344)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

- 아기 고유 코드 생성 로직을 따로 구현해야 합니다.
- Response 및 예외처리는 일단 ok()로 통일했습니다, 추후 예외처리 진행하겠습니다
- providerId와 해당 정보(태명, 출산예정일 등등) 을 JSON으로 요청 시 DB에 등록되는 식으로 구현했습니다
- 응답값이 있다면 Response값도 따로 만들겠습니다.

2024-07-27 19:23 UTC, AppleMint98 commented
수정하겠습니다!!
- providerId 를 따로 Request로 안받아와도 될 것 같습니다 지울게여

2024-07-27 19:29 UTC, junyoungBae1 approved these changes
고생하셨습니다!! 
request 바뀌는 것으로 알고 있겠습니다!

2024-07-29 11:48 UTC, JGoo99 requested changes
이전 커밋이랑 중복됐어요ㅜㅜ
rebase 랑 커밋 최신화(application-secret 업데이터)해서 올리면 좋을 것 같습니다!
수고하셨어요!!

2024-07-29 11:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/baby/repository/BabyRepository.java
> +  Baby findByCode(String code);
Optional<Baby> 로 받으면 null 처리를 안 할 경우 컴파일 에러가 뜨기 때문에 NPE 에 더 안전한 코드가 될 수 있어요!
그리고 서비스 단에서 코드 작성할 때도 if 문으로 감싸지 않고 바로 처리 가능합니당

```java
// repository
Optional<Baby> findByCode(String code);

// service
Baby baby = babyRepository.findByCode(babyCode)
      .orElseThrow(() -> new RuntimeException("Baby not found"));
```

2024-07-29 11:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/login/controller/LoginController.java
> +  public ResponseEntity<String> verifyBabyCode(@RequestBody BabyCodeRequest request) {
프론트에서 응답값이 필요하지 않다면 void 로 반환해도 될 것 같아요. `ResponseEntity<BaseResponse<Void>>`

2024-07-29 11:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/member/model/dto/BabyCodeRequest.java
> +@Data
noArgs, getter 정도만 달아도 될 것 같아요!

2024-07-29 11:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/member/service/MemberService.java
> +    return baby.getCode();
string 값을 그대로 전달하기보다는 dto 에 담아서 전체적인 응답 통일성을 이루면 좋을 것 같아요.
(이 메서드는 void 처리가 더 깔끔해보이네요!)

2024-07-29 11:48 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/member/service/MemberService.java
> +  public Member assignFamilyRole(String providerId, String familyRole) {
응답이 필요한 경우가 아니면 void 로 수정이 필요해보입니다!

2024-07-29 14:25 UTC, rlagkswn00 approved these changes
고생하셨습니다!
전체적으로 무난해보이네용
다만, 회원가입 시 모든 정보에 대해서 매번 서버와 통신할지, 클라이언트에서 모든 정보를 한번에 넘길 지 클라이언트와 의논해봐야 할거 같습니다.

혹시나 회원가입 중간에 앱을 끄고 처음부터 실행하였을 때 데이터베이스가 필요없는 값들이 저장될거 같아요

2024-07-29 14:25 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/login/controller/LoginController.java
> +    return ResponseEntity.ok().build();
그냥 Void로 반환값을 통일하기보단, 일관적인 응답을 위해 BaseResponse를 추가해서 사용하면 좋을거 같습니다.

2024-07-29 14:25 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/member/service/MemberService.java
> +
다시 Save를 직접 해주지 않아도, JPA Dirty Checking에 의해 자동으로 트랜잭션 종료 시 수정될 거 같아요!

2024-07-29 14:25 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/member/service/MemberService.java
> +  }
전체적으로 Member와 Baby 객체를 가져올 때 @JGoo99 말대로 Optional로 감싸서 가져오는 것이 조금 더 효율적인 코드가 될거 같습니다!

2024-07-31 10:38 UTC, JGoo99 approved these changes

2024-08-02 18:50 UTC, merged