[Feature] AuthenticationUtil
KUIT-AGARANG/Agarang-Backend pull request #56
Opened 2024-07-27 13:47 UTC by AppleMint98

## #️⃣연관된 이슈

> ex) #55 

## 📝작업 내용

> AuthenticationUtil 클래스로 파라미터를 받아오지않고 ProviderId 받아오기 

- API 작성 시, ProviderId 가 필요하시면 다음과 같이 사용하시면 됩니다.
```
String providerId = AuthenticationUtil.getProviderId();
String role = AuthenticationUtil.getRole();
```

2024-07-27 13:51 UTC, AppleMint98 commented
AuthenticationUtil 클래스만 보시면 됩니당

2024-07-27 15:17 UTC, rlagkswn00 approved these changes
고생하셨습니다!!
다만 static으로 해야할 이유가 없다면 빈 등록해서 사용해도 될거같습니당

2024-07-27 19:00 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/login/controller/MyController.java
`MainController` `MyController`의 용도가 무엇인지 궁금합니다!

2024-07-29 11:56 UTC, JGoo99 requested changes
수고많으셨습니다! 이 pr 도 머지 전에 rebase & 최신화 부탁드립니다!!

2024-07-31 01:39 UTC, closed without merging