[Feature] 노래 즐겨찾기, 삭제 기능 API 구현 및 리팩토링
KUIT-AGARANG/Agarang-Backend pull request #80
Opened 2024-08-07 17:34 UTC by junyoungBae1

## #️⃣연관된 이슈

[#63](https://github.com/KUIT-AGARANG/Agarang-Backend/issues/63)

<br/>

## 📝작업 내용

- PlaylistTracksResponse 클래스에 totalTrackCount와 totalTrackTime 필드를 추가하여 플레이리스트의총 노래 개수와 총 재생 시간을 확인할 수 있도록 기능을 추가했습니다.

- MemoryId를 통해 음악 즐겨찾기 기능을 추가하였습니다.
    - 즐겨찾기시 “내 마음에 쏙 드는” 플레이리스트에도 추가되도록 기능을 추가하였습니다.

- 삭제 요청시 MusicBookmark와 해당 플레이리스트에서 삭제하도록 기능을 추가하였습니다.

- 전체 플레이리스트 조회시 플레이리스트 안에 음악이 있는 경우만 조회되도록 수정하였습니다.

<br/>

<br/>

## 💬리뷰 요구사항(선택)

- api작동 되는 것까진 확인했습니다! 
- commit을 엉망으로 해버려서 message랑 내용이 많이 다를 수 있습니다..!

2024-08-08 00:26 UTC, AppleMint98 approved these changes
정말 고생하셨습니다 !!!

2024-08-08 00:26 UTC, applemint98 commented on src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
> +  INVALID_PLAYLIST_ID(false, HttpStatus.NOT_FOUND, 4010, "존재하지 않는 플레이리스트입니다."),
4009, 4010 위에랑 겹쳐요!!
제가 위치를 이상한데 놨네여 ㅋㅋㅋㅋ 수정하겠슴다

2024-08-08 00:26 UTC, applemint98 commented on src/main/java/com/kuit/agarang/domain/playlist/controller/PlaylistController.java
> +        PlaylistTracksResponse playlistTracksResponse = playlistService.getPlaylistTracks(id, details.getMemberId());
`@AuthenticationPrincipal` 이거 진짜 좋더라구요ㅋㅋㅋ

2024-08-08 00:26 UTC, applemint98 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +                .sorted(Comparator.comparing(PlaylistDto::getId)) // ID 순서대로 정렬
`Comparator.comparing(PlaylistDto::getId)` 처음알았습니다! 좋네요!!

2024-08-08 00:26 UTC, applemint98 commented on src/main/java/com/kuit/agarang/domain/memory/repository/MusicBookmarkRepository.java
> +    MusicBookmark findByMemory(Memory memory);
다른 분들이 알려주셨는데 Optional로 감싸서 반환하면 좋을 것 같습니다!!
```
Optional<MusicBookmark> 
```

이런 식입니다!!
관련 링크 입니당 https://dev-coco.tistory.com/178

2024-08-08 00:26 UTC, AppleMint98 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +    @Transactional
영한이 햄이 알려주신내용인데, 읽기전용 메서드에는 `@Transactional(readOnly = true)` 을 붙이는게 좋을 것 같습니다
다른 `getXxx()` 메서드에도 `@Transactional(readOnly = true)` 어노테이션을 붙여도 좋을 것 같습니다!!
다른 수정/삭제 메서드에는 다 붙여주셨기 때문에 클래스에  위 어노테이션을 붙이면 될 것 같슴다
```
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
```
이런 식입니다 !!

--- 
라고 알고있었는데, 관련 링크를 첨부하면서 배운점이 있어서 공유합니다!
https://medium.com/@jkha7371/is-transactional-readonly-true-a-silver-bullet-1dbf130c97f8

그냥 붙이는게 좋은줄로만 알았는데, 링크 2. Should we always add ~ 부분에 
서비스에다가 @Transactional(readOnly = true) 붙이면 서비스 계층의 메서드가 끝날 때 까지 연결을 해제하지 않아서
DB 연결에 안좋기 때문에 서비스에 시간이 오래걸리는 로직이 있는 경우 사용을 조심해야한다고 하네요!!
저희는 시간을 오래 잡아먹는 로직은 여기는 없어서 붙이셔도 좋을 듯 싶습니다(?)!

2024-08-08 00:26 UTC, AppleMint98 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +        }
findByMemory의 리턴값을 Optional로 받아서 !=null 대신 `.isPresent()` 나 `.isEmpty()` 등으로 하는게 더 이쁠거같습니다 ㅎㅎ

2024-08-08 08:58 UTC, rlagkswn00 requested changes
고생하셨습니다!
몇가지 질문드린 점이 있어서 우선 RC해둘게요!
문제 없으면 다시 Approve하겠습니당

2024-08-08 08:58 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/playlist/controller/PlaylistController.java
>      public ResponseEntity<BaseResponse<PlaylistTracksResponse>> getPlaylistTracks(@PathVariable Long id,
특정 플레이리스트 조회면, 뒤에 track을 붙이지 않고 `/api/playlists/{id}`로만 해도 충분히 의미 표시가 되는거 같습니당
1번 플레이리스트에 "트랙"이라는 개념을 조회하는 것처럼 보여서 약간 헷갈릴 여지가 있는거 같아욤

2024-08-08 08:58 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +        Playlist favoritePlaylist = playlistRepository.findById(2L)
나중에 수정해햐아할 부분인거같습니당

2024-08-08 08:58 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +        } else {
return 하고 메서드를 종료시키는게 조금 더 가독성 좋을거 같다는 생각입니당

그리고 즐겨찾기 업데이트면 MusicBookmark만 수정하면 되는 부분인거 같은데 혹시 MemoryPlaylist도 삭제하는 이유가 있나여?

2024-08-11 14:06 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/memory/repository/MusicBookmarkRepository.java
> +    MusicBookmark findByMemory(Memory memory);
사용해서 바꾸도록 하겠습니다!

2024-08-11 14:06 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/controller/PlaylistController.java
>      public ResponseEntity<BaseResponse<PlaylistTracksResponse>> getPlaylistTracks(@PathVariable Long id,
{id}까지만 해도 괜찮겠네요. 넵!

2024-08-11 14:08 UTC, junyoungBae1 commented on src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
> +        } else {
MemoryPlaylist 즐겨찾기(내 맘에 쏙 드는) 플레이리스트에서 제거하기 위해서 넣었습니다!

2024-08-11 14:44 UTC, rlagkswn00 approved these changes

2024-08-12 08:48 UTC, AppleMint98 approved these changes

2024-08-15 05:53 UTC, rlagkswn00 commented
시간관계상 우선 Merge 하겠습니다 수정사항은 새로 작업해주세영

2024-08-15 05:53 UTC, merged