JPA 도메인 설계
KUIT-AGARANG/Agarang-Backend pull request #9
Opened 2024-07-10 10:38 UTC by AppleMint98

## #️⃣연관된 이슈

> ex) #8 JPA 도메인 설계

## 📝작업 내용

> JPA 도메인 설계 
- BaseEntity (createdAt, updatedAt, status) 
=> 공통속성은 BaseEntity 클래스를 만들어 따로 관리하고, 이를 상속받도록 구현했습니다

- ERD 기반 엔티티 생성 

### 스크린샷 (선택)

![image](https://github.com/KUIT-AGARANG/Agarang-Backend/assets/141808008/d1427c2c-26b5-4116-850c-9327487382c6)

## 💬리뷰 요구사항(선택)

- application.yml, HealthCheckController 파일을 주석처리한 뒤, MySQL 로컬DB 로 생성 확인 했습니다. 

- JPA 양방향 매핑? -> 일단 단방향으로 하고, 필요시 추가하는 방향으로 고려하겠습니다. 일단 단방향으로만 했습니다 

- Member 테이블이 RefreshTokenId를 FK로 관리하도록 수정
=> 더 자주 조회되는 쪽에 FK로 설정하는게 권장된다고 해서 바꿔놨습니다

2024-07-10 14:27 UTC, rlagkswn00 approved these changes
고생하셨습니다!
전반적으로 엔티티 설계는 잘 되었다고 생각합니다!
추가적인 몇가지 생각들 리뷰로 남겼습니다!

그리고, 양방향 매핑은 성호님 생각과 동일합니당😀
yml같은 경우 @JGoo99 님이 더 좋은 코멘트 남겨주실거 같아서 스킵하겠습니당

리뷰는 확인 후 반영할 부분만 확인해주시면 될거 같아서 Approve 남겨용!

2024-07-10 14:27 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/common/model/entity/BaseEntity.java
> +@SuperBuilder
당장 하위 클래스에서 Builder 패턴 사용하는게 아니면 빼놔도 괜찮을거 같습니다.

2024-07-10 14:27 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/common/model/entity/BaseEntity.java
> +@AllArgsConstructor(access = AccessLevel.PROTECTED)
`BaseEntity`를 비롯해서 다른 `Entity` 클래스에 전체 생성자가 필요한가요??
JPA 엔티티 생성간 기본 생성자만 필수인걸로 아는데, 전체 생성자도 필수가 아니라면 뺴두고, 필요할때 사용하는 것이 좋다고 생각합니다.

2024-07-10 14:27 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/common/model/entity/BaseEntity.java
> +  private String status = "Active";
Status는 EnumClass로 작성해서 관리하는것도 좋은 방법일거 같습니다.

2024-07-10 14:27 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/common/model/entity/BaseEntity.java
> +public class BaseEntity {
직접 사용할 클래스가 아니면 abstract로 선언하는것도 좋을거 같습니다!

2024-07-10 14:27 UTC, rlagkswn00 commented on src/main/java/com/kuit/agarang/domain/member/model/entity/Member.java
> +  @JoinColumn
Join시 사용할 컬럼명 지정해두면 좋을거 같습니다.
아래 링크 내용이 잘 정리되어 있어 남깁니다!
[관련 링크](https://ksh-coding.tistory.com/105#%E2%9C%85%202-1.%20name%20%3A%20%EB%A7%A4%ED%95%91%ED%95%A0%20%EC%99%B8%EB%9E%98%20%ED%82%A4%20%EC%9D%B4%EB%A6%84%20%EC%A7%80%EC%A0%95%C2%A0-1)

2024-07-10 15:00 UTC, JGoo99 requested changes
다대다 관계 어떻게 구현하는지 궁금했는데,,,이렇게 하는거였군요. 빠르게 작업해주셔서 감사합니다!!! 코멘트 부분만 확인하고 멘션 부탁드립니다!

2024-07-10 15:00 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/common/model/entity/BaseEntity.java
> +  private String status = "Active";
> 1) `Application.java` 파일에 @EnableJpaAuditing 필요.

실행해보니 아래와 같은 에러가 뜨는데,

```
org.springframework.dao.DataIntegrityViolationException: not-null property references a null or transient value : com.kuit.agarang.domain.baby.model.entity.Character.createdAt
```
찾아보니까 @EntityListeners 를 사용하려면 먼저 실행되는 `Application.java` 파일에 @EnableJpaAuditing 이 있어야 인식이 되는 것 같아요! 확인 부탁드려요.

<br/>

> 2) status null 로 저장되는 현상.

테스트로 엔티티 하나 저장해보니 status 가 null 로 저장되더라구요.
개인적으로 기록하고싶어서 해결 방법을 노션에 적어두었는데 링크 남길게요! [트러블슈팅](https://goo99.notion.site/BaseEntity-NULL-66fcc6dd992141a4871053a32f136d09?pvs=4)

2024-07-10 15:00 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/baby/model/entity/Baby.java
> +  private Character character;
JoinColumn 에 name 속성을 characters_id 로 지정해야하나 싶어서 테스트해봤는데 설정 안해도 괜찮더라구요.

baby 의 FK, Character 의 PK 모두 `character_id` 로 생성되던데 테이블명을 `characters` 로 지정하면 어떤 장점이 있나요??? 궁금합니다!

2024-07-10 15:00 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/baby/model/entity/Baby.java
> +  private LocalDate date; // 출산 예정일
gpt 에게 도움을 요청하니 expectedDueDate 를 추천해줬어요!ㅋㅋㅎㅎ

2024-07-10 15:00 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/member/model/entity/Member.java
> +  private String role;
나중에 Enum 으로 생성해도 좋을 것 같아요! (저장할 땐 string 변환)

2024-07-10 15:00 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/memory/model/entity/Memory.java
> +  private String instrumentType;
이외의 종류가 다양하고, 정해져있는 필드는 enum 으로 생성하면 좋을 것 같습니다!!

2024-07-10 15:03 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/common/model/entity/BaseEntity.java
> +@SuperBuilder
같은 의견이에요!
BaseEntity 는 직접 생성해서 수정할 일이 없기 때문에,
BaseEntity 에서 SuperBuilder 랑 생성자 전부 뺀 후 abstract class 로 수정하고, 
다른 하위 클래스는 SuperBuilder -> Builder 로 수정하면 좋을 것 같아요.

2024-07-11 04:47 UTC, AppleMint98 commented
## 수정사항
BaseEntity
- `@SuperBuilder` 제거
- 추상클래스 변경
- `@AllArgsConstructor` 제거
- Status Enum 클래스 변경 -> "Active", "Inactive" 일단 두개 

기타 엔티티
- `@AllArgsConstructor` 제거
- `@SuperBuilder` -> `@Builder` 변경 
- JoinColumn명 지정 (name = ...)

Baby
- date -> expectedDueAt

Character
- Table(name = "`character`") 변경 
- 엔티티 이름을 character 그대로 갈까요 characters 로 바꿀까요? -

테이블명 characters 바꾼 이유 
-> CommandAcceptanceException 발생
-> create table character 쿼리를 날릴때 character로 테이블명이 지정되면 character가 예약어라 쓸 수 없다는 오류 
-> check the manual that corresponds to your MySQL server version for the right syntax to use near 'character' 
-> (name = "`character`") 이런식으로 앞뒤에 백틱을 사용해서 만들 수 있는데, s 없는거로 수정하겠습니당

`@Builder` 클래스 -> 생성자 레벨로 변경 
https://velog.io/@mooh2jj/%EC%98%AC%EB%B0%94%EB%A5%B8-%EC%97%94%ED%8B%B0%ED%8B%B0-Builder-%EC%82%AC%EC%9A%A9%EB%B2%95

AgarangApplication
- `@EnableJPAAuditing` 추가 

Enum타입 추가 
- Status, 음악생성 선택지들

2024-07-11 04:48 UTC, AppleMint98 commented on src/main/java/com/kuit/agarang/common/model/entity/BaseEntity.java
> +@SuperBuilder
수정했습니다!!

2024-07-11 05:19 UTC, rlagkswn00 commented
수고하셨습니다!
다음 커밋부터 노션에 있는 커밋 컨벤션을 반영하면 더 좋을거같아용

2024-07-11 06:46 UTC, JGoo99 approved these changes

2024-07-11 06:46 UTC, JGoo99 commented on src/main/java/com/kuit/agarang/domain/playlist/model/entity/Playlist.java
> +  }
관련 이슈 남겨주셔서 덕분에 공부했어요! 감사합니다ㅎ

기존에 설계 잘 해주셔서 원래대로 유지해도
AllArgsConstructer 에 access 레벨로 private 나 protected 가 붙어있기 때문에 관련 이슈는 방지할 수 있을 것 같아요!
(외부에서 전체 생성자 사용이 불가능, 빌더로만 가능, 따라서 필드가 섞여서 할당될 위험x)

지금은 필드가 2-3개 여서 괜찮지만, 필드가 많아지면 코드 자체도 길어지고, 계속 수정하는 것이 혹시나 번거로울까봐 코멘트 남깁니다!!

2024-07-11 06:57 UTC, merged